name = "LeanReasoningSandbox"
version = "0.1.0"
defaultTargets = ["leanreasoningsandbox"]

[[lean_lib]]
name = "LeanReasoningSandbox"

[[lean_exe]]
name = "leanreasoningsandbox"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"
